---
- name: Watch for new CR in ServiceNow
  hosts: localhost
  sources:
    - name: Listen to ServiceNow
      cloin.eda.snow_records:
        instance: "{{ snow_instance }}"
        username: "{{ snow_username }}"
        password: "{{ snow_password }}"
        # query: "{{ query }}"
        table: change_request
        interval: 1
  rules:
    - name: Add BigIP Pool
      condition: event.short_description == "Add pool"
      actions:
        - debug:
            var: event
        - run_workflow_template:
            organization: "{{ organisation_name }}"
            name: "{{ job_template_name }}"
            job_args:
              extra_vars:
                survey_action: "add"
                survey_ci_sys_id: "{{ event.cmdb_ci.value }}"
                survey_change_number: "{{ event.number }}"

    - name: Del BigIP Pool
      condition: event.short_description == "Delete pool"
      actions:
        - debug:
            var: event
        - run_job_template:
            organization: "{{ organisation_name }}"
            name: "{{ job_template_name }}"
            job_args:
              extra_vars:
                survey_action: "delete"
                survey_vm_name: "{{ event.cmdb_ci }}"

    - name: Debug everything else
      condition: event.cmdb_ci is not defined
      action:
        debug:
          var: event

