---
- name: Close SNow Change Request
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Place a change request in ServiceNow in Review
      servicenow.itsm.change_request:
        state: review
        number: "{{ survey_change_number }}"
      delegate_to: localhost

    - name: Close a change request
      servicenow.itsm.change_request:
        state: closed
        number: "{{ survey_change_number }}"
        close_code: "successful"
        close_notes: "Closed"
      delegate_to: localhost
