---
- name: Close SNow Change Request
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Retrieve a specific configuration item by sys_id
      servicenow.itsm.configuration_item_info:
        sys_id: "{{ survey_ci_sys_id }}"
      register: result

    # - name: debug
    #   debug:
    #     msg: "{{ result }}"

    - name: Set CI detail
      ansible.builtin.set_stats:
        data:
          survey_vm_name: "{{ result.records[0].name }}"
          survey_vm_address: "{{ result.records[0].ip_address }}"
          survey_f5_pool_name: "{{ result.records[0].category }}"
        aggregate: no
