---
- name: Update SNow Change Request
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: Update to assess the change request in ServiceNow
      servicenow.itsm.change_request:
        state: assess
        number: "{{ survey_change_number }}"
        assignment_group: CAB Approval
      register: change_request_status
      
    # - name: Check the status
    #   servicenow.itsm.change_request_info:
    #     number: "{{ survey_change_number }}"
    #   register: change_request_status

    - name: Display Change Approval Detail
      ansible.builtin.debug:
        msg: "You have a new CR Approval request. Please click on this URL to approve: {{ lookup('env', 'SN_HOST') }}nav_to.do?uri=change_request.do?sysparm_query=number={{ change_request_status.record.number }}"

    - name: Wait for Change Request approval
      servicenow.itsm.change_request_info:
        number: "{{ survey_change_number }}"
      until: change_request_status.records[0].state == "scheduled"
      retries: 50
      delay: 10
      register: change_request_status

    - name: Update to implement the change request in ServiceNow
      servicenow.itsm.change_request:
        state: implement
        number: "{{ survey_change_number }}"
        assignment_group: CAB Approval
